version: '3.7'

services:
    db:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOME_DIR: ${POSTGRES_HOME_DIR}
            POSTGRES_PORT: ${POSTGRES_PORT}
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_PORT}'
        volumes:
            - ${POSTGRES_HOME_DIR}:/var/lib/postgresql/data
